pipeline {
    agent any

    stages {
        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKERHUB_CREDENTIALS_USR', passwordVariable: 'DOCKERHUB_CREDENTIALS_PSW')]) {
                    sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                }
            }
        }
        stage('Build & Push Dockerfile') {
            steps {
                dir('DevOps-Pipeline-PHP/laravel-app') {
                    sh 'ansible-playbook playbook.yml'
                }
            }
        }
        stage('Run Docker Compose Playbook') {
            steps {
                dir('DevOps-Pipeline-PHP/laravel-app/') {
                    sh 'ansible-playbook playbook-dcompose.yml'
                }
            }
        }
    }
}
