
Vagrant.configure("2") do |config|

  # Provider
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
    # vb.cpu = 2
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end
    
  # Box
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/xenial64"


  # Network
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 9090, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.56.10"
  # config.vm.network "public_network"

  # Share Dir
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provision
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2
  SHELL
end
