pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                sh "cd DevOps-Pipeline/"
            }
        }
        stage('Build & push Dockerfile') {
            steps {
                sh "ansible-playbook playbook.yml"
            }
        }
        stage('Run Dockercompose') {
            steps {
                echo 'Dockercompose Running'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying'
            }
        }
    }
}
