pipeline {
    agent any

    stages {
        stage('Build & push Dockerfile') {
            steps {
                sh """
                cd DevOps-Pipeline/
                ansible-playbook playbook.yml
                """
            }
        }
        stage('Run Dockercompose') {
            steps {
                echo 'Dockercompose Running'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying'
            }
        }
    }
}
