pipeline {
    agent any

    stages {

      stage('Delete Deployment') {
          steps {
            // You will need to install CloudBees AWS Credentials Plugin in Jenkins and add AWS Credentials first 
              withCredentials([[
                $class: 'AmazonWebServicesCredentialsBinding',
                credentialsId: "aws-credentials",
                accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                ]]) {
                sh """
                kubectl delete deploy --all -n kasten-io || true
                """
                
              }
          }
      }

      stage('Delete Service') {
          steps {
            // You will need to install CloudBees AWS Credentials Plugin in Jenkins and add AWS Credentials first 
              withCredentials([[
                $class: 'AmazonWebServicesCredentialsBinding',
                credentialsId: "aws-credentials",
                accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                ]]) {
                sh """
                kubectl delete service --all -n kasten-io || true
                """
              }
          }
      }

      stage('Delete Kasten Namespace') {
          steps {
            // You will need to install CloudBees AWS Credentials Plugin in Jenkins and add AWS Credentials first 
              withCredentials([[
                $class: 'AmazonWebServicesCredentialsBinding',
                credentialsId: "aws-credentials",
                accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                ]]) {
                sh """
                kubectl delete namespace kasten-io
                """
              }
          }
      }
  }
}